# Generated by Django 2.2.10 on 2021-05-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_message_privatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevRubric',
            fields=[
            ],
            options={
                'ordering': ['-name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bboard.rubric',),
        ),
    ]
